### ISSUE TITLE
Example data

### ISSUE THREAD

**Issue by angelpavon97** [rueycheng/AdaRank#1]
I have been trying to use the algorithm but I am not sure how the dataset should look like. Could you provide an example dataset for training and testing? Or at least, could you provide more information about what are X, y and qid types?

Thank you in advance <3

**Comment by rueycheng** [comment]
Hi @angelpavon97, I guess you're asking what input format the script `test.py` takes? The input is assumed to be in svmlight format. Have a look at this webpage for more info http://www.cs.cornell.edu/people/tj/svm_light/svm_rank.html

The script should work with any off-the-shelf learning-to-rank datasets. As an example, you can download the Letor 4.0 dataset from this website https://www.microsoft.com/en-us/research/project/letor-learning-rank-information-retrieval/. Then you do:
```
unrar x MQ2007.rar
python test.py MQ2007/Fold1/{train,vali,test}.txt
``` 
You will then get some NDCG scores from the output. Hope that helps.

**Comment by angelpavon97** [comment]
Thank you very much!
