### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by jmdu99** [rueycheng/AdaRank#2]
Hi,

I am trying to use this AdaRank implementation which seems amazing.
However, when I try to train the model, I get a `ValueError`. 

My code is:
   ```
    X, y, qid = load_svmlight_file(train_file, query_id=True)
    print('X shape:', X.shape)
    print('y shape:', y.shape)
    print('qid shape:', qid.shape)
    
    X_test, y_test, qid_test = load_svmlight_file(test_file, query_id=True)

    scorer = NDCGScorer(k=10)
    
    '''
    Run AdaRank for 100 iterations optimizing for NDCG@10. 
    When no improvement is made within the previous 10 iterations, 
    the algorithm will stop.
    '''
    model = AdaRank(max_iter=100, estop=10, scorer=scorer).fit(X, y, qid)
```

The shapes of my data are:
```
X shape: (140, 105)
y shape: (140,)
qid shape: (140,)
```
The error happens in line:
`model = AdaRank(max_iter=100, estop=10, scorer=scorer).fit(X, y, qid)`

The error is:
`ValueError: shapes (3,) and (91,) not aligned: 3 (dim 0) != 91 (dim 0)`

Specifically, the error is in this line of the library:
`weighted_average = np.dot(weights, score)`

When I try to debug in the library, I get these:
```
Number of queries: 3
Weights shape: (3,)
Number of weak ranker scores: 105
```
And inside  `for fid, score in enumerate(weak_ranker_score):`:

```
fid: 0
Score shape: (91,)
```

So it seems that there is a problem of sizes between `weights `and `scores`, but I don't know what's going on. 

I have **3** different qid, **140** documents for training with **105** features each one. 

Hope you can help me,
Thanks in advance

**Comment by rueycheng** [comment]
Hey @jmdu99, my best guess is that the qid's are scattered - usually for learning to rank the same qids are placed together to form contiguous blocks, and maybe your data wasn't formatted that way? Check if your `qid` is like: `[0, 0, ..., 0, 1, 1, ..., 1, 2, 2, ..., 2]`.

Alternatively, you can also run this snippet to print out the number of query blocks:
```
print(len(list(utils.group_offsets(qid))))
```
If it doesn't match the number of queries, better check again and be sure the data is laid out in an expected order.

**Comment by jmdu99** [comment]
That seems to be the problem. There are 3 blocks before splitting. 

But when applying `train_test_split` the number of blocks increases:
 ```
# Split documents, labels, and query_ids into training (70%) and testing (30%)
 X_train, X_test, y_train, y_test, qid_train, qid_test= train_test_split(X, y, qid, test_size=0.3, random_state=1, shuffle=True, stratify=qid)
```
Is there any way of sorting the split by `qid` in order to have only 3 blocks or another way of splitting?

Thanks in advance

**Comment by jmdu99** [comment]
Thank you @rueycheng. That was the problem. 

Now I have another problem in line `pred = model.predict(X_test, qid_test)`
I will open another issue if I don't manage to solve it
