### ISSUE TITLE
Display ranking

### ISSUE THREAD

**Issue by jmdu99** [rueycheng/AdaRank#3]
Hi @rueycheng 

Finally, I have managed to get the nDCG scores from `k = 1` to` k = 20`

Now, I would like to display a ranking with the results. 

I have tried this:
   ```
# Return ranking
    docno = load_docno(test_file, letor=True)
    print_trec_run(qid_test, docno, pred, output=open(ranking_file, 'wb')) 
```
However, docnos cant' be found in my `test_file` (`docno `array is empty)

In `print_trec_run`:
`format(qid=qid[i], docno=docno[i], rank=rank, sim=pred[i], run_id=run_id))`

I get this error:
`IndexError: index 7 is out of bounds for axis 0 with size 0`

I have seen that docnos follow one of these patterns:
```
docno_pattern = re.compile(r'#\s*docid\s*=\s*(\S+)')
docno_pattern = re.compile(r'#\s*(\S+)')
```

However, I think there are no docnos in my **test file** :(

It looks like this:
```
0 qid:1 65:0.8635398447491647 88:0.5042806128839266
0 qid:1 0:0.4336122872341365 1:0.5701433653876129 5:0.464003602765715 39:0.4336122872341365 68:0.2044479985767591 81:0.2044479985767591
0 qid:1 0:0.4116103074959742 4:0.5412136437389908 39:0.4116103074959742 67:0.5412136437389908 68:0.1940740750173357 81:0.1940740750173357
0 qid:1 60:0.351932125005294 68:0.2570511854639458 74:0.5833888176004248 76:0.6353350635618945 81:0.2570511854639458
0 qid:1 20:0.2779414512496159 24:0.5269511067979753 37:0.5269511067979753 63:0.2995265310626487 92:0.5269511067979753
0 qid:1 20:0.5645782010909166 94:0.8253795822849901
```

How could I get a ranking with this test file? or  What could I do in order to change the test file format?

Thanks in advance.

**Comment by rueycheng** [comment]
Hi @jmdu99, docno's are absolutely needed when you request a dumpout in TREC-format run output. I suppose you're gonna need them for qrels too.

You can just come up with your own docno's. For example, something like this might just work:
```
0 qid:1 65:0.8635398447491647 88:0.5042806128839266 # docid=1
...
0 qid:1 20:0.5645782010909166 94:0.8253795822849901 # docid=6
```

Have a look at the documentation of trec_eval or any other tools that would consume TREC run file for more details. Hope that helps.

**Comment by jmdu99** [comment]
Perfect, I will have a look at the documentation. Thank you.
